# Generated by Django 4.2 on 2023-05-23 08:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Puesto')),
                ('empresa', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('fecha_desde', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('ubicacion', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['fecha_desde'],
            },
        ),
    ]
